// Каталог товаров TYAG МОСКВА
const PRODUCTS = [

  // ===== ОДНОРАЗОВЫЕ — INFLAVE =====
  { id: 'inflave-omega-10000-new', name: 'INFLAVE OMEGA 10000', brand: 'Inflave', flavor: 'Новинка', category: 'disposable',
    price: 1250, oldPrice: 1450, image: 'inflave-omega-10000-new', colors: ['#ff7c2a','#ffb84d'], puffs: 10000, nicotine: '2%', isNew: true },
  { id: 'inflave-omega-10000-cranberry-mint', name: 'INFLAVE OMEGA 10000', brand: 'Inflave', flavor: 'Клюква, мята', category: 'disposable',
    price: 1250, image: 'inflave-omega-10000-cranberry-mint', colors: ['#2acfff','#5cffd2'], puffs: 10000, nicotine: '2%' },
  { id: 'inflave-omega-10000-grape-aloe', name: 'INFLAVE OMEGA 10000', brand: 'Inflave', flavor: 'Виноград, алоэ', category: 'disposable',
    price: 1250, image: 'inflave-omega-10000-grape-aloe', colors: ['#ff5c9b','#a06bff'], puffs: 10000, nicotine: '2%' },
  { id: 'inflave-air-6000-strawberry', name: 'INFLAVE AIR 6000', brand: 'Inflave', flavor: 'Клубничное чудо', category: 'disposable',
    price: 1050, image: 'inflave-air-6000-strawberry', colors: ['#ff5c9b','#9b5cff'], puffs: 6000, nicotine: '2%' },
  { id: 'inflave-air-6000-raspberry', name: 'INFLAVE AIR 6000', brand: 'Inflave', flavor: 'Спелая малина', category: 'disposable',
    price: 1050, image: 'inflave-air-6000-raspberry', colors: ['#ff3a8a','#ff7c2a'], puffs: 6000, nicotine: '2%' },

  // ===== ОДНОРАЗОВЫЕ — PUFFMI =====
  { id: 'puffmi-tobacco', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Tobacco', category: 'disposable',
    price: 990, image: 'puffmi-tobacco', colors: ['#8b6a3a','#222'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-matcha-mint', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Matcha Mint Ice', category: 'disposable',
    price: 990, image: 'puffmi-matcha-mint', colors: ['#5cff8a','#3aa6ff'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-acai-peach', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Acai Peach Pitaya', category: 'disposable',
    price: 990, image: 'puffmi-acai-peach', colors: ['#a06bff','#ff5c9b'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-watermelon-ice', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Watermelon Ice', category: 'disposable',
    price: 990, image: 'puffmi-watermelon-ice', colors: ['#ff5c5c','#5cff8a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-razz-cola', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Razz Cola', category: 'disposable',
    price: 990, image: 'puffmi-razz-cola', colors: ['#7a3a3a','#222'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-ginger-beer', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Ginger Beer', category: 'disposable',
    price: 990, image: 'puffmi-ginger-beer', colors: ['#ffb800','#ff7c2a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-apple-pear', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Apple Pear', category: 'disposable',
    price: 990, image: 'puffmi-apple-pear', colors: ['#5cff8a','#ffd24d'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-salted-lemon', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Salted Lemon', category: 'disposable',
    price: 990, image: 'puffmi-salted-lemon', colors: ['#ffd24d','#ffb800'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-lemon-mint', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Lemon Mint', category: 'disposable',
    price: 990, image: 'puffmi-lemon-mint', colors: ['#ffd24d','#5cff8a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-mojito-lychee', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Mojito Lychee', category: 'disposable',
    price: 990, image: 'puffmi-mojito-lychee', colors: ['#ff8ad6','#5cff8a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-cherry-peach-lemon', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Cherry Peach Lemon', category: 'disposable',
    price: 990, image: 'puffmi-cherry-peach-lemon', colors: ['#ff5c9b','#ffd24d'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-green-mango', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Green Mango', category: 'disposable',
    price: 990, image: 'puffmi-green-mango', colors: ['#5cff8a','#ffd24d'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-mixed-prunus', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Mixed Prunus', category: 'disposable',
    price: 990, image: 'puffmi-mixed-prunus', colors: ['#a06bff','#ff5c9b'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-strawberry-grapefruit', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Strawberry Grapefruit', category: 'disposable',
    price: 990, image: 'puffmi-strawberry-grapefruit', colors: ['#ff5c9b','#ff7c2a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-mango-guava', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Mango Guava', category: 'disposable',
    price: 990, image: 'puffmi-mango-guava', colors: ['#ffd24d','#ff7c2a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-raspberry-grape', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Raspberry Grape', category: 'disposable',
    price: 990, image: 'puffmi-raspberry-grape', colors: ['#a06bff','#ff5c9b'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-pineapple-lemon-watermelon', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Pineapple Lemon Watermelon', category: 'disposable',
    price: 990, image: 'puffmi-pineapple-lemon-watermelon', colors: ['#ffd24d','#5cff8a'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-siberian-berries', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Siberian Berries', category: 'disposable',
    price: 990, image: 'puffmi-siberian-berries', colors: ['#a06bff','#3aa6ff'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-apple-guava', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Apple Guava', category: 'disposable',
    price: 990, image: 'puffmi-apple-guava', colors: ['#5cff8a','#ffb800'], puffs: 9000, nicotine: '2%' },
  { id: 'puffmi-strawberry-sundae', name: 'PUFFMI 9000', brand: 'Puffmi', flavor: 'Strawberry Sundae', category: 'disposable',
    price: 990, image: 'puffmi-strawberry-sundae', colors: ['#ff5c9b','#ff7c2a'], puffs: 9000, nicotine: '2%' },

  // ===== ОДНОРАЗОВЫЕ — WOKO / ALOK / WAKA =====
  { id: 'woko-60000-strawberry-watermelon', name: 'WOKO 60000', brand: 'Woko', flavor: 'Strawberry Watermelon', category: 'disposable',
    price: 1990, oldPrice: 2290, image: 'woko-60000-strawberry-watermelon', colors: ['#ff3a8a','#ff5c5c'], puffs: 60000, nicotine: '2%', isNew: true },
  { id: 'alok-50000-sour-peach-watermelon', name: 'ALOK 50000', brand: 'Alok', flavor: 'Кислый персик, арбуз', category: 'disposable',
    price: 1850, image: 'alok-50000-sour-peach-watermelon', colors: ['#ff7c2a','#ff5c5c'], puffs: 50000, nicotine: '2%' },
  { id: 'alok-50000-cranberry-ice', name: 'ALOK 50000', brand: 'Alok', flavor: 'Клюква со льдом', category: 'disposable',
    price: 1850, image: 'alok-50000-cranberry-ice', colors: ['#ff3a3a','#3aa6ff'], puffs: 50000, nicotine: '2%' },
  { id: 'waka-soflo', name: 'WAKA SoFlo', brand: 'Waka', flavor: 'Одноразовая система', category: 'disposable',
    price: 590, image: 'waka-soflo', colors: ['#222','#ffd24d'], puffs: 1800, nicotine: '2%' },
  { id: 'waka-mirai', name: 'WAKA Mirai', brand: 'Waka', flavor: 'Одноразовая система', category: 'disposable',
    price: 1290, image: 'waka-mirai', colors: ['#fff','#888'], puffs: 6000, nicotine: '2%' },

  // ===== ОДНОРАЗОВЫЕ — SNOWWOLF / GEEK BAR =====
  { id: 'snowwolf-smart-ic-15k', name: 'SNOWWOLF Smart IC 15K', brand: 'Snowwolf', flavor: '15 вкусов, smart-дисплей', category: 'disposable',
    price: 1650, image: 'snowwolf-smart-ic-15k', colors: ['#ff5c9b','#5c5cff'], puffs: 15000, nicotine: '2%' },
  { id: 'geekbar-pulse-r', name: 'GEEK BAR Pulse R', brand: 'Geek Bar', flavor: '25 000 затяжек', category: 'disposable',
    price: 1450, image: 'geekbar-pulse-r', colors: ['#3a5cff','#1a1a99'], puffs: 25000, nicotine: '2%' },
  { id: 'geekbar-50000', name: 'GEEK BAR 50000', brand: 'Geek Bar', flavor: 'До 50 000 затяжек', category: 'disposable',
    price: 1990, image: 'geekbar-50000', colors: ['#ffd24d','#ff7c2a'], puffs: 50000, nicotine: '2%', isNew: true },
  { id: 'geekbar-pulse-16k-32k', name: 'GEEK BAR Pulse 16K/32K', brand: 'Geek Bar', flavor: 'Dual Mode 16K/32K', category: 'disposable',
    price: 1550, image: 'geekbar-pulse-16k-32k', colors: ['#3a5cff','#5cd2ff'], puffs: 32000, nicotine: '2%' },

  // ===== МНОГОРАЗОВЫЕ — GEEK VAPE =====
  { id: 'geekvape-aegis-hero-2', name: 'GEEKVAPE Aegis Hero 2', brand: 'GeekVape', flavor: 'Pod-мод 45W', category: 'reusable',
    price: 2890, image: 'geekvape-aegis-hero-2', colors: ['#ff3a3a','#5cffd2'] },
  { id: 'geekvape-wenax-k1-se', name: 'GEEKVAPE Wenax K1 SE Luxury', brand: 'GeekVape', flavor: 'Pod-система Midnight Green', category: 'reusable',
    price: 1690, image: 'geekvape-wenax-k1-se', colors: ['#3a5c5c','#222'] },
  { id: 'geekvape-aegis-boost-3', name: 'GEEKVAPE Aegis Boost III', brand: 'GeekVape', flavor: 'Pod-мод Sapphire Blue', category: 'reusable',
    price: 3490, image: 'geekvape-aegis-boost-3', colors: ['#3a5cff','#222'] },
  { id: 'geekvape-h45', name: 'GEEKVAPE H45', brand: 'GeekVape', flavor: '4ml 45W, Light Green', category: 'reusable',
    price: 2290, image: 'geekvape-h45', colors: ['#5cff8a','#222'] },
  { id: 'geekvape-h45-classic', name: 'GEEKVAPE H45 Classic', brand: 'GeekVape', flavor: '45W Sakura', category: 'reusable',
    price: 2190, image: 'geekvape-h45-classic', colors: ['#ff8ad6','#222'] },
  { id: 'geekvape-aegis-boost', name: 'GEEKVAPE Aegis Boost', brand: 'GeekVape', flavor: 'Pod-мод Red & White', category: 'reusable',
    price: 2790, image: 'geekvape-aegis-boost', colors: ['#ff3a3a','#fff'] },

  // ===== ЖИДКОСТИ =====
  { id: 'jam-monster-grape', name: 'JAM MONSTER', brand: 'Jam Monster', flavor: 'Виноградный джем · 100мл',
    category: 'liquid', price: 890, image: 'jam-monster-grape', colors: ['#7a3aff','#3a1a99'], volume: '100мл', nicotine: '3мг' },
  { id: 'jam-monster-apple', name: 'JAM MONSTER', brand: 'Jam Monster', flavor: 'Яблочный джем · 100мл',
    category: 'liquid', price: 890, image: 'jam-monster-apple', colors: ['#5cff5c','#1a991a'], volume: '100мл', nicotine: '3мг' },
  { id: 'husky-mint', name: 'HUSKY Mint Fusion', brand: 'Husky', flavor: 'Мята · Лайм',
    category: 'liquid', price: 690, image: 'husky-mint', colors: ['#5cffd2','#1a4d4d'], volume: '30мл', nicotine: '20мг' },
  { id: 'rell-watermelon', name: 'RELL Salt', brand: 'Rell', flavor: 'Арбуз',
    category: 'liquid', price: 590, image: 'rell-watermelon', colors: ['#ff5c5c','#ff8a5c'], volume: '28мл', nicotine: '20мг' },
  { id: 'maxwells-mango', name: 'MAXWELLS Cassiopeia', brand: 'Maxwells', flavor: 'Манго · Маракуйя',
    category: 'liquid', price: 1190, image: 'maxwells-mango', colors: ['#ffb800','#ff5cb9'], volume: '60мл', nicotine: '3мг' },
  { id: 'brusko-strawberry', name: 'BRUSKO Salt', brand: 'Brusko', flavor: 'Клубничный взрыв',
    category: 'liquid', price: 490, image: 'brusko-strawberry', colors: ['#ff5c9b','#ff5c5c'], volume: '30мл', nicotine: '20мг' },
  { id: 'cloud-parrot-blue', name: 'CLOUD PARROT', brand: 'Cloud Parrot', flavor: 'Черника',
    category: 'liquid', price: 1090, image: 'cloud-parrot-blue', colors: ['#3a5cff','#1a1a99'], volume: '120мл', nicotine: '3мг' },
  { id: 'duty-free-tropical', name: 'DUTY FREE', brand: 'Duty Free', flavor: 'Тропический микс',
    category: 'liquid', price: 790, image: 'duty-free-tropical', colors: ['#ffd24d','#5cff8a'], volume: '60мл', nicotine: '3мг' },

  // ===== АКСЕССУАРЫ =====
  { id: 'usb-c-cable', name: 'Кабель USB Type-C', brand: 'TYAG', flavor: 'Зарядка 1м',
    category: 'accessory', price: 290, image: 'usb-c-cable', colors: ['#5c5c66','#222'] },
  { id: 'lanyard-strap', name: 'Шнурок для устройств', brand: 'TYAG', flavor: 'Универсальный, на шею',
    category: 'accessory', price: 190, image: 'lanyard', colors: ['#ff5c5c','#1a1a1a'] },
  { id: 'case-silicone', name: 'Силиконовый чехол', brand: 'TYAG', flavor: 'Для одноразок',
    category: 'accessory', price: 250, image: 'case-silicone', colors: ['#5cff8a','#1a1a1a'] },
  { id: 'battery-18650', name: 'Аккумулятор 18650', brand: 'Molicel', flavor: '3000mAh · 35A',
    category: 'accessory', price: 650, image: 'battery-18650', colors: ['#888','#444'] },
  { id: 'charger-dual', name: 'Зарядное устройство', brand: 'Nitecore', flavor: 'Двухслотовое',
    category: 'accessory', price: 1490, image: 'charger-dual', colors: ['#1a1a1a','#ffb800'] },
  { id: 'drip-tip-510', name: 'Дрип-тип 510', brand: 'TYAG', flavor: 'Делрин, чёрный',
    category: 'accessory', price: 350, image: 'drip-tip-510', colors: ['#1a1a1a','#5c5c66'] },

  // ===== РАСХОДНИКИ =====
  { id: 'xros-pod', name: 'Картридж XROS', brand: 'Vaporesso', flavor: '0.6Ω / 0.8Ω · 4 шт',
    category: 'consumable', price: 390, image: 'xros-pod', colors: ['#1f9fff','#1a1a1a'] },
  { id: 'caliburn-pod', name: 'Картридж Caliburn', brand: 'Uwell', flavor: '0.8Ω / 1.0Ω · 4 шт',
    category: 'consumable', price: 350, image: 'caliburn-pod', colors: ['#3a5cff','#1a1a1a'] },
  { id: 'xlim-pod', name: 'Картридж XLIM', brand: 'OXVA', flavor: '0.6Ω / 0.8Ω · 3 шт',
    category: 'consumable', price: 370, image: 'xlim-pod', colors: ['#7a5cff','#1a1a1a'] },
  { id: 'gtx-coil', name: 'Испаритель GTX', brand: 'Vaporesso', flavor: '0.2Ω / 0.4Ω · 5 шт',
    category: 'consumable', price: 290, image: 'gtx-coil', colors: ['#ff5c5c','#1a1a1a'] },
  { id: 'cotton-bacon', name: 'Вата Cotton Bacon', brand: 'Wick\'N\'Vape', flavor: 'Premium 10 листов',
    category: 'consumable', price: 490, image: 'cotton-bacon', colors: ['#f4f4f4','#aaa'] },
  { id: 'wire-kanthal', name: 'Проволока Kanthal A1', brand: 'Geek Vape', flavor: '0.4мм · 10м',
    category: 'consumable', price: 290, image: 'wire-kanthal', colors: ['#a0a0a8','#444'] }
];

const CATEGORIES = [
  { id: 'disposable', name: 'Одноразовые', cover: 'inflave-omega-10000-new',           colors: ['#ff5c9b','#a06bff'] },
  { id: 'reusable',   name: 'Многоразовые', cover: 'geekvape-aegis-boost-3',           colors: ['#3aa6ff','#5c5cff'] },
  { id: 'liquid',     name: 'Жидкости',     cover: 'jam-monster-grape',                colors: ['#ffb800','#ff5c5c'] },
  { id: 'accessory',  name: 'Аксессуары',   cover: 'charger-dual',                     colors: ['#5cff8a','#3aa6ff'] },
  { id: 'consumable', name: 'Расходники',   cover: 'xros-pod',                         colors: ['#a06bff','#ff5c9b'] }
];

function getCategoryName(id) { const c = CATEGORIES.find(x => x.id === id); return c ? c.name : ''; }
function getCategoryCount(id) { return PRODUCTS.filter(p => p.category === id).length; }
function formatPrice(p) { return p.toLocaleString('ru-RU') + ' ₽'; }
