// Auto-generated by scripts/fetch-brand-logos.mjs — do not edit by hand.
// Maps brand name (as in products.ts) -> /public/ relative path to logo.

export const BRAND_LOGOS: Record<string, string> = {
  "ELFBAR": "/assets/logos/elfbar.ico",
  "GEEKBAR": "/assets/logos/geekbar.ico",
  "GEEK VAPE": "/assets/logos/geek-vape.ico",
  "VAPORESSO": "/assets/logos/vaporesso.ico",
  "VOZOL": "/assets/logos/vozol.ico",
  "WAKA": "/assets/logos/waka.ico",
  "PUFFMI": "/assets/logos/puffmi.ico",
  "FIZZY": "/assets/logos/fizzy.ico"
};
