// Auto-generated by scripts/fetch-brand-logos.mjs — do not edit by hand.
// Maps brand name (as in products.ts) -> /public/ relative path to logo.

export const BRAND_LOGOS: Record<string, string> = {};
