// Auto-generated: maps dish slug -> uploaded photo filename.
export const DISH_IMAGES: Record<string, string> = {
  "bruschetta-salmon": "bruschetta-salmon.jpg",
  "bruschetta-shrimp": "bruschetta-shrimp.jpg",
  "bruschetta-ricotta": "bruschetta-ricotta.jpg",
  "bruschetta-assorti": "bruschetta-assorti.webp",
  "shrimp-pate": "shrimp-pate.jpg",
  "spicy-shrimp": "spicy-shrimp.jpg",
  "vongole-cheese": "vongole-cheese.jpg",
  "vongole-tomato": "vongole-tomato.jpg",
  "halloumi": "halloumi.jpg",
  "cheese-plate": "cheese-plate.jpg",
  "fruit-plate": "fruit-plate.jpg",
  "meat-plate": "meat-plate.webp",
  "pickles": "pickles.jpg",
  "bowl-salmon": "bowl-salmon.webp",
  "salad-bacon": "salad-bacon.jpg",
  "salad-eggplant": "salad-eggplant.jpg",
  "waldorf": "waldorf.webp",
  "bowl-shrimp": "bowl-shrimp.jpg",
  "risotto": "risotto.png",
  "tagliatelle": "tagliatelle.jpg",
  "carbonara": "carbonara.webp",
  "pasta-shrimp": "pasta-shrimp.jpg",
  "beef-steak": "beef-steak.jpg",
  "salmon-sousvide": "salmon-sousvide.webp",
  "napoleon": "napoleon.webp",
  "ice-cream": "ice-cream.jpg",
  "candy": "candy.webp",
};
