import type { Category, Product } from "./types";

export const CATEGORIES: { id: Category; label: string; subtitle: string; image: string }[] = [
  {
    id: "disposable",
    label: "Одноразки",
    subtitle: "120+ позиций",
    image: "https://vapesultan.com/wp-content/uploads/2025/02/Waka-SoPro-20000.jpg",
  },
  {
    id: "pod",
    label: "Многоразки",
    subtitle: "15 моделей",
    image: "https://store.vaporesso.com/cdn/shop/files/XROS3_LemonYellow_2.png?v=1763950530",
  },
  {
    id: "liquid",
    label: "Жидкости",
    subtitle: "Соль и фри-база",
    image: "https://images.unsplash.com/photo-1567721913486-6585f069b332?w=600&q=80&auto=format",
  },
  {
    id: "accessory",
    label: "Аксессуары",
    subtitle: "Зарядки, чехлы",
    image: "https://images.unsplash.com/photo-1606136540942-39e95b9c87f8?w=600&q=80&auto=format",
  },
  {
    id: "sale",
    label: "Распродажа",
    subtitle: "До −40%",
    image: "https://img.staticdj.com/e9bbf41af2caed20549e73fdc6a18c1e.jpeg",
  },
  {
    id: "cartridge",
    label: "Картриджи",
    subtitle: "Сменные блоки",
    image: "https://store.vaporesso.com/cdn/shop/files/XROS_0.8_MESH_Pod-3ml_new.png?v=1761554021",
  },
];

export const CATEGORY_LABEL: Record<Category, string> = {
  disposable: "Одноразки",
  pod: "Поды-системы",
  cartridge: "Картриджи",
  sale: "Распродажа",
  liquid: "Жидкости",
  accessory: "Аксессуары",
};

const DUALL_FLAVORS = [
  "Спрайт арбуз лайм", "Морозный личи", "Печенье карамель", "Морозный дыня",
  "Личи гуава", "Табак печенье", "Малиновый йогурт", "Мятные леденцы эвкалипт",
  "Дыня маракуйя", "Клубничное мороженое", "Киви гуава", "Ягодный чай",
  "Ананас киви", "Холодное смородина", "Манго ананас", "Смородина малина яблоко",
  "Клубника апельсин маракуйя", "Мятная жвачка", "Ягодный морс", "Ледяной арбуз с дыней",
  "Морозный ред булл", "Морозный ананас", "Йогурт персик маракуйя", "Манго апельсин мята",
  "Кислый лимон киви", "Лимонад с грейпфрутом", "Ледяной тархун", "Манго кумкват",
  "Фруктовый мармелад", "Яблоко виноград", "Ледяная кола", "Экзотические фрукты",
  "Яблоко малина", "Ледяное манго", "Чай с грейпфрутом и ягодами", "Клубничный йогурт",
  "Ледяное манго с апельсином", "Черничный чизкейк",
];

const FIZZY_FLAVORS = [
  "Банан", "Чёрная смородина", "Красное яблоко ягоды", "Алое манго дыня",
  "Черника гранат", "Ананас", "Личи лимон", "Апельсиновый сок граната",
  "Арбуз", "Капучино", "Виноград ананасовый лёд", "Ежевика шелковица",
  "Энергетик", "Черника малина вишня", "Зелёная оливковая мята", "Радужная конфета",
  "Персик", "Клюквенная сода", "Ананас персик маракуйя", "Малина клубника апельсин",
];

const ELFBAR_FLAVORS = [
  "Персик-холодок", "Виноград-холодок", "Мята сладкая", "Двойное яблоко",
  "Вишня-арбуз", "Лимон-лайм", "Арбуз-холодок", "Кола-лайм",
  "Гранатовый всплеск", "Виноград-малина", "Киви-маракуйя-гуава",
  "Клубника-киви-холодок", "Манго-персик-арбуз", "Черника-малина-холодок",
  "Арбуз-канталупа-гуава",
];

const BUBBLEMON_FLAVORS = [
  "Berry Ice", "Blackberry Kiwi Fruit", "Blackberry Sweet Orange", "Black Grape",
  "Cantaloupe", "Coconut", "Cranberry Grape", "Guava",
  "Lemon Blueberry", "Lemon Passion Fruit Peach", "Orange Mango", "Orange",
  "Pear Mango", "Pineapple Coconut", "Pink Lemonade", "Red Peach",
  "Strawberry Watermelon", "Блестящая клубника", "Клубничный мускат", "Личи",
];

const LAISKA_FLAVORS = [
  "Жевательные конфеты", "Яблочная груша", "Черничный энергетик", "Вишнёвая газировка",
  "Черника малина лимон", "Ледяной арбуз", "Малина лайм", "Чизкейк",
  "Клюква виноград", "Ежевичный чай", "Лимон с морской солью", "Фантазия",
];

export const PRODUCTS: Product[] = [
  {
    slug: "duall-salt",
    brand: "DUALL",
    name: "DUALL SALT",
    category: "disposable",
    price: 185,
    isHot: true,
    shortDesc: "Жидкость на солевом никотине — 2% и 5%",
    description:
      "DUALL SALT — линейка одноразовых устройств с яркими вкусами и стабильной парогенерацией. Доступно в крепкости 2% и 5%. Идеален для розницы и опта.",
    strength: "2% / 5%",
    flavors: DUALL_FLAVORS,
    variants: [
      { label: "2% никотин", price: 185 },
      { label: "5% никотин", price: 185 },
    ],
    tags: ["Бестселлер", "38 вкусов"],
    features: ["Солевой никотин", "Honeycomb-испаритель", "Type-C зарядка"],
    imageStyle: { from: "#e94e3c", via: "#7b1f15", to: "#1a0a08", accent: "#ffd2c8" },
  },
  {
    slug: "waka-8000",
    brand: "WAKA",
    name: "WAKA 8 000 затяжек",
    category: "disposable",
    price: 520,
    isNew: true,
    isHot: true,
    shortDesc: "Новинка серии WAKA — 8 000 затяжек",
    description:
      "Серия WAKA — премиальные одноразки с увеличенной ёмкостью. Тонкий корпус, soft-touch покрытие, плотный пар.",
    puffs: 8000,
    variants: [
      { label: "Микс вкусов", price: 520 },
      { label: "От 100 шт", price: 500, note: "опт" },
    ],
    tags: ["Новинка", "8 000 затяжек"],
    features: ["Mesh-coil", "Регулируемый поток", "Type-C 1A"],
    imageStyle: { from: "#0ea5a8", via: "#0b3d52", to: "#08161e", accent: "#a3f5ee" },
  },
  {
    slug: "waka-20000",
    brand: "WAKA",
    name: "WAKA 20 000 затяжек",
    category: "disposable",
    price: 750,
    isNew: true,
    shortDesc: "Серия WAKA — увеличенная ёмкость",
    description: "Большой ресурс работы, чёткий вкусопередатчик, до 20 000 затяжек.",
    puffs: 20000,
    variants: [
      { label: "Микс вкусов", price: 750 },
      { label: "От 100 шт", price: 720, note: "опт" },
    ],
    tags: ["Новинка", "20 000"],
    imageStyle: { from: "#9333ea", via: "#3b1170", to: "#0f0420", accent: "#e9d5ff" },
  },
  {
    slug: "waka-25000",
    brand: "WAKA",
    name: "WAKA 25 000 затяжек",
    category: "disposable",
    price: 770,
    isNew: true,
    shortDesc: "Серия WAKA 25 000 — флагман линейки",
    description: "Премиум-сегмент: 25 000 затяжек, OLED-индикатор, металлический корпус.",
    puffs: 25000,
    variants: [
      { label: "Микс вкусов", price: 770 },
      { label: "От 100 шт", price: 740, note: "опт" },
    ],
    tags: ["Новинка", "Hit"],
    imageStyle: { from: "#0891b2", via: "#0b3a4a", to: "#06141c", accent: "#bef3ff" },
  },
  {
    slug: "waka-60000",
    brand: "WAKA",
    name: "WAKA 60 000 затяжек",
    category: "disposable",
    price: 1020,
    isNew: true,
    isHot: true,
    shortDesc: "Топовая модель WAKA — 60 000 затяжек",
    description:
      "Максимальный ресурс работы среди одноразок. Двойной аккумулятор, индикатор заряда и жидкости. От 1 000 шт — цена по запросу.",
    puffs: 60000,
    variants: [
      { label: "Микс вкусов", price: 1020 },
      { label: "От 100 шт", price: 1000, note: "опт" },
      { label: "От 1 000 шт", price: 0, note: "по запросу" },
    ],
    tags: ["Топ", "60 000"],
    features: ["Двойной аккумулятор", "OLED-дисплей", "Mesh 2.0"],
    imageStyle: { from: "#f59e0b", via: "#7a3e09", to: "#1a0c02", accent: "#ffe6a8" },
  },
  {
    slug: "fizzy-great-10000",
    brand: "FIZZY",
    name: "FIZZY Great 10 000",
    category: "sale",
    price: 280,
    oldPrice: 420,
    isSale: true,
    shortDesc: "Распродажа — 20 ярких вкусов",
    description:
      "FIZZY Great 10 000 — компактная одноразка с насыщенным вкусом и чёткой парогенерацией. Действует акция: скидка 30%.",
    puffs: 10000,
    flavors: FIZZY_FLAVORS,
    tags: ["−33%", "Хит распродажи"],
    features: ["Mesh-coil", "Type-C зарядка", "Регулируемый поток"],
    imageStyle: { from: "#ec4899", via: "#7a1d4b", to: "#1a0512", accent: "#ffd1ea" },
  },
  {
    slug: "elfbar-monnight-25000",
    brand: "ELFBAR",
    name: "ELFBAR Monnight 25 000",
    category: "disposable",
    price: 610,
    isHot: true,
    shortDesc: "Русский язык на дисплее · 15 вкусов",
    description:
      "ELFBAR Monnight 25 000 — флагман с OLED-экраном, поддержкой русского языка интерфейса и стабильной парогенерацией до 25 000 затяжек.",
    puffs: 25000,
    flavors: ELFBAR_FLAVORS,
    tags: ["OLED", "Русский язык"],
    features: ["OLED дисплей RU", "Mesh-coil 0.8", "Type-C 1.5A"],
    imageStyle: { from: "#22c55e", via: "#11512a", to: "#05140c", accent: "#bdf5cf" },
  },
  {
    slug: "geekbar-40000",
    brand: "GEEKBAR",
    name: "GEEKBAR 40 000",
    category: "disposable",
    price: 650,
    shortDesc: "5% · Русский язык · Честный знак · 15 вкусов",
    description: "Премиальный GEEKBAR с расширенным ресурсом до 40 000 затяжек.",
    puffs: 40000,
    strength: "5%",
    tags: ["Честный знак"],
    imageStyle: { from: "#a855f7", via: "#3a1668", to: "#0d041c", accent: "#e9d4ff" },
  },
  {
    slug: "geekbar-50000",
    brand: "GEEKBAR",
    name: "GEEKBAR 50 000",
    category: "disposable",
    price: 670,
    isHot: true,
    shortDesc: "5% · Русский язык · Честный знак · 15 вкусов",
    description: "Топовая модель GEEKBAR с ресурсом 50 000 затяжек.",
    puffs: 50000,
    strength: "5%",
    tags: ["Хит", "Честный знак"],
    imageStyle: { from: "#f97316", via: "#7a3408", to: "#1a0a02", accent: "#ffd4a8" },
  },
  {
    slug: "vozol-shisha-25000",
    brand: "VOZOL",
    name: "Vozol Shisha 25 000",
    category: "disposable",
    price: 550,
    shortDesc: "2% · Русский язык · Честный знак · 20 вкусов",
    description:
      "Vozol Shisha — кальянная подача пара, насыщенный вкус, до 25 000 затяжек. Маркировка Честный знак.",
    puffs: 25000,
    strength: "2%",
    tags: ["Кальянная подача", "20 вкусов"],
    imageStyle: { from: "#14b8a6", via: "#0a4a44", to: "#031412", accent: "#aef0e8" },
  },
  {
    slug: "bubble-mon-30000",
    brand: "BUBBLE MON",
    name: "Bubble Mon 30 000",
    category: "disposable",
    price: 400,
    isNew: true,
    shortDesc: "Корейский бренд · 2 вкуса в одном · 5% · 20 вкусов",
    description:
      "Bubble Mon 30 000 — корейская одноразка с уникальной функцией двух вкусов в одном устройстве. Стабильный пар и стильный дизайн.",
    puffs: 30000,
    strength: "5%",
    flavors: BUBBLEMON_FLAVORS,
    tags: ["Korea", "2-in-1"],
    features: ["Двойной вкус", "Mesh-coil", "Type-C зарядка"],
    imageStyle: { from: "#f43f5e", via: "#7a0f23", to: "#1a040a", accent: "#ffcfd8" },
  },
  {
    slug: "puffmi-pure-12000",
    brand: "PUFFMI",
    name: "Puffmi Pure 12 000",
    category: "disposable",
    price: 350,
    shortDesc: "5% · Русский язык · 20 вкусов",
    description: "Puffmi Pure — компактный корпус, чёткий вкус, до 12 000 затяжек.",
    puffs: 12000,
    strength: "5%",
    tags: ["20 вкусов"],
    imageStyle: { from: "#06b6d4", via: "#063d4c", to: "#02131a", accent: "#bef0ff" },
  },
  {
    slug: "laiska-queen-10000",
    brand: "LAISKA",
    name: "Laiska Queen 10 000",
    category: "disposable",
    price: 350,
    shortDesc: "5% · 12 вкусов",
    description: "Laiska Queen 10 000 — стильная одноразка с насыщенными вкусами.",
    puffs: 10000,
    strength: "5%",
    flavors: LAISKA_FLAVORS,
    tags: ["12 вкусов"],
    imageStyle: { from: "#eab308", via: "#5a3e07", to: "#1a1102", accent: "#fff1a8" },
  },
  {
    slug: "vaporesso-xros-mini",
    brand: "VAPORESSO",
    name: "XROS Mini",
    category: "pod",
    price: 620,
    shortDesc: "Компактная под-система от VAPORESSO",
    description: "VAPORESSO XROS Mini — классика жанра в pod-системах. Стабильный вкус, лёгкая замена картриджа.",
    tags: ["Pod-система"],
    imageStyle: { from: "#64748b", via: "#1f2937", to: "#0a0f17", accent: "#cbd5e1" },
  },
  {
    slug: "vaporesso-xros-3-mini",
    brand: "VAPORESSO",
    name: "XROS 3 Mini",
    category: "pod",
    price: 740,
    shortDesc: "Третье поколение XROS Mini",
    description: "Улучшенный аккумулятор и быстрая зарядка.",
    tags: ["Pod-система"],
    imageStyle: { from: "#475569", via: "#1f2937", to: "#0a0f17", accent: "#cbd5e1" },
  },
  {
    slug: "vaporesso-xros-4",
    brand: "VAPORESSO",
    name: "XROS 4",
    category: "pod",
    price: 1240,
    isNew: true,
    shortDesc: "Флагман линейки XROS 4",
    description: "XROS 4 — крупный аккумулятор, регулируемая мощность, премиальные материалы.",
    tags: ["Флагман"],
    imageStyle: { from: "#1d4ed8", via: "#0b1f4e", to: "#020616", accent: "#bdd0ff" },
  },
  {
    slug: "vaporesso-xros-4-mini",
    brand: "VAPORESSO",
    name: "XROS 4 Mini",
    category: "pod",
    price: 840,
    shortDesc: "Компактная версия XROS 4",
    description: "Лёгкий корпус, всё та же мощность серии XROS 4.",
    tags: ["Компакт"],
    imageStyle: { from: "#2563eb", via: "#0b1f4e", to: "#020616", accent: "#bdd0ff" },
  },
  {
    slug: "vaporesso-xros-5",
    brand: "VAPORESSO",
    name: "XROS 5",
    category: "pod",
    price: 1290,
    isNew: true,
    shortDesc: "Новое поколение XROS",
    description: "Регулировка обдува, OLED-экран, поддержка картриджей предыдущих поколений.",
    tags: ["Новинка"],
    imageStyle: { from: "#7c3aed", via: "#2a0b6b", to: "#0a041c", accent: "#d4c4ff" },
  },
  {
    slug: "vaporesso-xros-5-mini",
    brand: "VAPORESSO",
    name: "XROS 5 Mini",
    category: "pod",
    price: 860,
    shortDesc: "Mini-версия XROS 5",
    description: "Та же платформа XROS 5 в компактном корпусе.",
    tags: ["Компакт"],
    imageStyle: { from: "#6d28d9", via: "#2a0b6b", to: "#0a041c", accent: "#d4c4ff" },
  },
  {
    slug: "geekvape-boost-le",
    brand: "GEEK VAPE",
    name: "Boost LE",
    category: "pod",
    price: 820,
    shortDesc: "Compact pod-система Boost LE",
    description: "Лимитированная версия популярной серии Boost.",
    tags: ["Pod-система", "LE"],
    imageStyle: { from: "#4f46e5", via: "#1e1b4b", to: "#0a0a1c", accent: "#c7c4ff" },
  },
  {
    slug: "geekvape-hero-3-classic",
    brand: "GEEK VAPE",
    name: "Hero 3 Classic",
    category: "pod",
    price: 1580,
    shortDesc: "Третье поколение Hero",
    description: "Классика Geek Vape Hero — теперь с улучшенным аккумулятором.",
    tags: ["Pod-система"],
    imageStyle: { from: "#1f2937", via: "#111827", to: "#030712", accent: "#9ca3af" },
  },
  {
    slug: "geekvape-hero-2-new",
    brand: "GEEK VAPE",
    name: "Hero 2 (новые)",
    category: "pod",
    price: 1750,
    isNew: true,
    shortDesc: "Обновлённая партия Hero 2",
    description: "Обновлённая партия Hero 2 — фабричная пломба, оригинальные картриджи в комплекте.",
    tags: ["Новинка"],
    imageStyle: { from: "#475569", via: "#1f2937", to: "#0a0f17", accent: "#cbd5e1" },
  },
  {
    slug: "geekvape-hero-5",
    brand: "GEEK VAPE",
    name: "Hero 5",
    category: "pod",
    price: 1730,
    isNew: true,
    shortDesc: "Новое поколение Hero",
    description: "Hero 5 — флагман серии: OLED-экран, увеличенная батарея.",
    tags: ["Флагман"],
    imageStyle: { from: "#7c3aed", via: "#2a0b6b", to: "#0a041c", accent: "#d4c4ff" },
  },
  {
    slug: "geekvape-boost-2",
    brand: "GEEK VAPE",
    name: "Boost 2 (B60)",
    category: "pod",
    price: 1480,
    shortDesc: "Pod-mod Boost 2 60W",
    description: "Boost 2 (B60) — pod-мод с регулировкой мощности до 60W.",
    tags: ["Pod-Mod", "60W"],
    imageStyle: { from: "#dc2626", via: "#7a1414", to: "#1a0404", accent: "#ffc4c4" },
  },
  {
    slug: "geekvape-boost-3",
    brand: "GEEK VAPE",
    name: "Boost 3",
    category: "pod",
    price: 2050,
    isNew: true,
    isHot: true,
    shortDesc: "Boost 3 — новинка линейки",
    description: "Boost 3 — топовый pod-мод с новой эргономикой и большим аккумулятором.",
    tags: ["Топ", "Новинка"],
    imageStyle: { from: "#16a34a", via: "#0b4a25", to: "#03140a", accent: "#bdf5cf" },
  },
];

export const BRANDS = Array.from(new Set(PRODUCTS.map((p) => p.brand))).sort();

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(c: Category): Product[] {
  if (c === "sale") return PRODUCTS.filter((p) => p.isSale);
  return PRODUCTS.filter((p) => p.category === c);
}

export function getRelated(slug: string, limit = 4): Product[] {
  const current = getProduct(slug);
  if (!current) return [];
  return PRODUCTS.filter(
    (p) => p.slug !== slug && (p.category === current.category || p.brand === current.brand),
  ).slice(0, limit);
}
