// Auto-generated by scripts/fetch-product-images.mjs — do not edit by hand.
// Maps product slug -> path under /public/ for the real product photo.
// Empty map means SVG fallbacks will be used.

export const PRODUCT_IMAGES: Record<string, string> = {};
