// Auto-generated by scripts/fetch-product-images.mjs — do not edit by hand.
// Maps product slug -> ordered array of image URLs (local /products/...).
// Refresh via: Actions → "Localize product images" → Run workflow.

export const PRODUCT_IMAGES: Record<string, string[]> = {
  "duall-salt": [
    "/products/duall-salt.jpg"
  ],
  "waka-8000": [
    "/products/waka-8000.jpg"
  ],
  "waka-20000": [
    "/products/waka-20000.webp"
  ],
  "waka-25000": [
    "/products/waka-25000.jpg"
  ],
  "waka-60000": [
    "/products/waka-60000.png"
  ],
  "fizzy-great-10000": [
    "/products/fizzy-great-10000.jpg"
  ],
  "elfbar-monnight-25000": [
    "/products/elfbar-monnight-25000.png"
  ],
  "geekbar-40000": [
    "/products/geekbar-40000.png"
  ],
  "geekbar-50000": [
    "/products/geekbar-50000.webp"
  ],
  "vozol-shisha-25000": [
    "/products/vozol-shisha-25000.webp"
  ],
  "bubble-mon-30000": [
    "/products/bubble-mon-30000.webp"
  ],
  "puffmi-pure-12000": [
    "/products/puffmi-pure-12000.png"
  ],
  "laiska-queen-10000": [
    "/products/laiska-queen-10000.png"
  ],
  "vaporesso-xros-mini": [
    "/products/vaporesso-xros-mini.png"
  ],
  "vaporesso-xros-3-mini": [
    "/products/vaporesso-xros-3-mini.png"
  ],
  "vaporesso-xros-4": [
    "/products/vaporesso-xros-4.jpg"
  ],
  "vaporesso-xros-4-mini": [
    "/products/vaporesso-xros-4-mini.png"
  ],
  "vaporesso-xros-5": [
    "/products/vaporesso-xros-5.jpg"
  ],
  "vaporesso-xros-5-mini": [
    "/products/vaporesso-xros-5-mini.webp"
  ],
  "geekvape-boost-le": [
    "/products/geekvape-boost-le.png"
  ],
  "geekvape-hero-3-classic": [
    "/products/geekvape-hero-3-classic.jpg"
  ],
  "geekvape-hero-2-new": [
    "/products/geekvape-hero-2-new.png"
  ],
  "geekvape-hero-5": [
    "/products/geekvape-hero-5.png"
  ],
  "geekvape-boost-2": [
    "/products/geekvape-boost-2.webp"
  ],
  "geekvape-boost-3": [
    "/products/geekvape-boost-3.png"
  ]
};
