// Auto-generated by scripts/fetch-product-images.mjs — do not edit by hand.
// Maps product slug -> ordered array of paths under /public/.
// The first entry is the primary photo (used in cards). Additional entries
// are used by ProductGallery for multi-angle product detail pages.

export const PRODUCT_IMAGES: Record<string, string[]> = {
  "bubble-mon-30000": ["/products/bubble-mon-30000.jpg","/products/bubble-mon-30000-2.jpg","/products/bubble-mon-30000-3.jpg"],
  "elfbar-monnight-25000": ["/products/elfbar-monnight-25000.jpg","/products/elfbar-monnight-25000-2.jpg","/products/elfbar-monnight-25000-3.jpg"],
  "vaporesso-xros-4": ["/products/vaporesso-xros-4.jpg"],
  "vaporesso-xros-4-mini": ["/products/vaporesso-xros-4-mini.jpg"],
  "waka-60000": ["/products/waka-60000.jpg","/products/waka-60000-2.jpg","/products/waka-60000-3.jpg"],
  "xros-cart-04-2": ["/products/xros-cart-04-2.jpg"],
};
