"""
Downloads every external URL in lib/product-images.ts to public/products/
and rewrites the .ts file to use local /products/<slug>[-idx].<ext> paths.
Runs in CI; the sandbox can't reach external hosts.
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MAP_FILE = ROOT / "lib" / "product-images.ts"
OUT_DIR = ROOT / "public" / "products"
OUT_DIR.mkdir(parents=True, exist_ok=True)

UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

EXT_FROM_CONTENT_TYPE = {
    "image/jpeg": "jpg",
    "image/jpg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
    "image/gif": "gif",
    "image/svg+xml": "svg",
}


def parse_map() -> dict[str, list[str]]:
    src = MAP_FILE.read_text()
    m = re.search(r"PRODUCT_IMAGES\s*:\s*Record<[^>]+>\s*=\s*(\{[\s\S]*?\});", src)
    if not m:
        raise SystemExit("could not find PRODUCT_IMAGES object in product-images.ts")
    # The object literal is valid JSON (no trailing commas in our generator).
    return json.loads(m.group(1))


def ext_from_url(url: str) -> str:
    path = urllib.parse.urlparse(url).path.lower()
    for ext in ("png", "jpg", "jpeg", "webp", "gif", "svg"):
        if path.endswith("." + ext):
            return "jpg" if ext == "jpeg" else ext
    return "jpg"


def download(url: str, max_attempts: int = 4) -> tuple[bytes, str]:
    delay = 2
    last_err: Exception | None = None
    for attempt in range(max_attempts):
        req = urllib.request.Request(
            url,
            headers={"User-Agent": UA, "Accept": "image/*,*/*;q=0.8"},
        )
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                data = resp.read()
                ctype = (resp.headers.get("Content-Type") or "").split(";")[0].strip().lower()
                ext = EXT_FROM_CONTENT_TYPE.get(ctype) or ext_from_url(url)
                return data, ext
        except urllib.error.HTTPError as e:
            last_err = e
            if e.code in (403, 429) or e.code >= 500:
                print(f"      attempt {attempt + 1}: HTTP {e.code} — sleeping {delay}s")
                time.sleep(delay)
                delay *= 2
                continue
            raise
        except Exception as e:
            last_err = e
            print(f"      attempt {attempt + 1}: {type(e).__name__}: {e} — sleeping {delay}s")
            time.sleep(delay)
            delay *= 2
    raise RuntimeError(f"giving up after {max_attempts} attempts") from last_err


def local_name(slug: str, idx: int, ext: str) -> str:
    return f"{slug}.{ext}" if idx == 0 else f"{slug}-{idx + 1}.{ext}"


def main() -> int:
    mapping = parse_map()
    new_mapping: dict[str, list[str]] = {}
    failed: list[tuple[str, str]] = []

    for slug, urls in mapping.items():
        new_urls: list[str] = []
        for i, url in enumerate(urls):
            # Skip entries that are already local-rooted.
            if url.startswith("/"):
                new_urls.append(url)
                print(f"  ✓ {slug}[{i}] kept local: {url}")
                continue

            print(f"  → {slug}[{i}] downloading {url[:80]}")
            try:
                data, ext = download(url)
            except Exception as e:
                print(f"    FAILED {type(e).__name__}: {e}")
                failed.append((slug, url))
                # Keep the original URL as a last-ditch fallback.
                new_urls.append(url)
                continue

            fname = local_name(slug, i, ext)
            out_path = OUT_DIR / fname
            out_path.write_bytes(data)
            new_urls.append(f"/products/{fname}")
            print(f"    saved /products/{fname} ({len(data)} bytes)")
            time.sleep(0.3)

        new_mapping[slug] = new_urls

    # Write the file back with deterministic 2-space indent, mirroring the
    # original generator's output.
    body = (
        "// Auto-generated by scripts/fetch-product-images.mjs — do not edit by hand.\n"
        "// Maps product slug -> ordered array of image URLs (local /products/...).\n"
        "// Refresh via: Actions → \"Localize product images\" → Run workflow.\n"
        "\n"
        f"export const PRODUCT_IMAGES: Record<string, string[]> = "
        f"{json.dumps(new_mapping, indent=2, ensure_ascii=False)};\n"
    )
    MAP_FILE.write_text(body)
    print(f"\nWrote {len(new_mapping)} mappings to {MAP_FILE}")

    if failed:
        print(f"\n{len(failed)} URLs failed (kept original):")
        for slug, url in failed:
            print(f"  {slug}: {url}")
        # Non-fatal — local copies of successful downloads are still written.
    return 0


if __name__ == "__main__":
    sys.exit(main())
